CREATE DATABASE login_db;
USE login_db;

CREATE TABLE usuarios (
    id INT AUTO_INCREMENT PRIMARY KEY,
    email VARCHAR(100) NOT NULL,
    senha VARCHAR(100) NOT NULL
);

CREATE TABLE Produtos (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    descricao TEXT,
    valor DECIMAL(10,2) NOT NULL,
    categoria VARCHAR(50),
    estoque INT DEFAULT 0,
    data_cadastro DATETIME DEFAULT CURRENT_TIMESTAMP,
    peso DECIMAL(6,2),
    largura DECIMAL(6,2),
    altura DECIMAL(6,2),
    profundidade DECIMAL(6,2)
);

INSERT INTO Produtos (nome, descricao, valor, categoria, estoque, peso, largura, altura, profundidade) VALUES
(
    'Bicicleta Mountain Bike Aro 29  ',
    'Bicicleta ideal para trilhas e uso urbano, aro 29, suspensão dianteira, 21 velocidades.',
    1499.90,
    'Ciclismo',
    15,
    13.50,
    25.00,
    90.00,
    110.00
),
(
	'Tênis de Corrida FlexRun 2000   ',
    'Leve e confortável, solado com amortecimento, ideal para corridas longas.',
    299.99,
    'Calçados',
    30,
    0.45,
    12.00,
    30.00,
    20.00
),
(	
	'Bola de Futebol Campo Pro Soccer',
    'Bola oficial de campo, tamanho 5, material durável e costuras termoplásticas.',
    89.90,
    'Futebol',
    50,
    0.42,
    22.00,
    22.00,
    22.00
),
(
	'Mochila Esportiva 30L UltraLight',
    'Mochila leve e resistente à água, com compartimento para laptop e hidratação.',
    149.90,
    'Acessórios',
    20,
    0.80,
    30.00,
    50.00,
    15.00
),
(
	'Barra de Proteína Whey Chocolate',
    'Barra de proteína sabor chocolate, 20g de whey protein por unidade.',
    7.50,
    'Nutrição',
    200,
    0.06,
    5.00,
    15.00,
    3.00
),
('Raquete de Tênis Wilson Pro',
 'Raquete profissional de tênis,
 ideal para jogadores avançados.',
 350.00,
 'Tênis',
 15,
 0.3,
 27.0,
 68.0,
 2.5
 ),
('Bola de Futebol Adidas Tango',
 'Bola de futebol oficial,
 modelo Tango, para jogos profissionais.', 
 120.00, 
 'Futebol', 
 50, 0.5, 
 22.0, 
 22.0,
 22.0),
('Tênis de Corrida Nike Air Zoom',
 'Tênis de corrida com tecnologia Air Zoom para amortecimento superior.', 
 450.00, 'Calçados', 
 30, 0.8,
 30.0, 10.0,
 12.0),
   ('Bola de Basquete Spalding NBA',
   'Bola de basquete oficial da NBA, para jogos profissionais.', 
   180.00, 'Basquete', 
   40, 0.6, 
   24.0,
   24.0, 
   24.0),
     ('Luvas de Boxe Everlast 12oz', 
     'Luvas de boxe Everlast, 
     tamanho 12oz, 
     para treinamento e sparring.', 
     220.00, 'Boxe',
     25, 1.2,
     25.0, 
     25.0, 
     15.0),
	('Raquete de Badminton Yonex Voltric',
	'Raquete de badminton Yonex Voltric,
	para jogadores intermediários.', 
	280.00, 'Badminton',
	20, 0.2,
	20.0, 
	70.0, 
	2.0),
	('Capacete de Ciclismo Giro Foray', 
    'Capacete de ciclismo Giro Foray, 
    modelo unissex, tamanho médio.', 
    150.00, 'Ciclismo',
    35, 
    0.3,
    25.0, 
    20.0, 
    15.0),
	('Mochila de Hidratação CamelBak Hydrobak', 
    'Mochila de hidratação CamelBak Hydrobak,
    capacidade de 1.5L.',
    250.00, 'Corrida',
    50, 0.5,
    30.0,
    40.0, 
    15.0),
	('Tênis de Futebol Society Puma Future', 
    'Tênis de futebol society Puma Future,
    modelo unissex.', 350.00, 'Calçados', 
    40, 0.9,
    32.0, 
    12.0, 
    14.0),
	('Bola de Vôlei Mikasa V200W',
    'Bola de vôlei Mikasa V200W,
    oficial da FIVB, 
    para jogos profissionais.',
    150.00,
    'Vôlei',
    60,
    0.4,
    22.0,
    22.0,
    22.0),
	('Raquete de Squash Tecnifibre Carboflex', 
    'Raquete de squash Tecnifibre Carboflex,
    para jogadores avançados.',
    400.00, 'Squash', 
    15, 0.25, 
    20.0, 
    70.0, 
    2.0),
	('Bola de Rugby Gilbert Xact', 
    'Bola de rugby Gilbert Xact, oficial para jogos profissionais.',
    100.00, 'Rugby', 
    30, 0.6,
    28.0,
    28.0,
    28.0),
	('Tênis de Corrida Asics Gel-Kayano', 
    'Tênis de corrida Asics Gel-Kayano, 
    modelo para estabilidade.', 
    500.00, 'Calçados',
    25,
    0.85,
    31.0,
    11.0,
    13.0),
	('Bola de Handebol Select Ultimate',
    'Bola de handebol Select Ultimate,
    oficial para jogos profissionais.',
    120.00, 'Handebol', 
    45, 
    0.5,
    22.0, 
    22.0, 
    22.0),
	('Raquete de Ping Pong Butterfly Timo Boll', 
    'Raquete de ping pong Butterfly Timo Boll, 
    para jogadores avançados.', 350.00, 
    'Tênis de Mesa', 
    20, 0.15,
    15.0, 
    30.0,
    2.0),
	('Bola de Futebol Americano Wilson GST',
    'Bola de futebol americano Wilson GST, 
    oficial para jogos profissionais.',
    200.00, 'Futebol Americano', 
    25,
    0.7, 
    28.0,
    28.0,
    28.0),
	('Tênis de Basquete Nike LeBron',
    'Tênis de basquete Nike LeBron, 
    modelo para alto desempenho.', 
    600.00, 'Calçados', 
    30, 1.0, 
    32.0, 
    12.0, 
    14.0),
	('Bola de Futebol de Areia Mikasa VLS300',
    'Bola de futebol de areia Mikasa VLS300,
    oficial para jogos profissionais.', 
    150.00,
    'Futebol de Areia',
    40,
    0.5, 
    22.0, 
    22.0,
    22.0),
	('Raquete de Tênis Babolat Pure Drive', 
    'Raquete de tênis Babolat Pure Drive, 
    para jogadores intermediários.', 
    350.00, 'Tênis', 
    35, 
    0.3,
    27.0,
    68.0, 
    2.5),
	('Bola de Futebol Nike Ordem', 
    'Bola de futebol Nike Ordem, 
    oficial para jogos profissionais.', 
    180.00, 'Futebol', 
    50, 0.5, 
    22.0, 
    22.0, 
    22.0);
    

INSERT INTO usuarios (email, senha) VALUES
('teste@email.com', '123456');

select * from usuarios;

SELECT * FROM Produtos;